**Question:** What event has most contributed to Maryland gymnastics' losses in recent seasons? How does that compare to other women's teams in the Big Ten?

There is a data set that exists with the NCAA women's gymnastics scores from the last ten years from the [Road to Nationals site.](https://roadtonationals.com/results/standings/) I downloaded it and put it into this folder. I think this data should have all of the scores I need to determine the events most impacting Maryland's performance and compare it to other teams in the conference.

If this data does not work, most of the data is on Maryland gymnastics' site, but that would require more to clean up and combine into one set.

Examples:

<https://dbknews.com/2024/02/26/maryland-gymnastics-big-five-season-low/>

This story explains a meet where Maryland performed badly, which could help me in identifying what trends might be best to look into when looking at their overall data.

<https://dbknews.com/2024/04/30/maryland-gymnastics-2024-season-recap/>

This story explains how Maryland managed to improve their performance after looking shaky mid-season. This could also be helpful in identifying certain events to look at when analyzing the data.

I can't find any stories that do any kind of in-depth data analysis covering several years regarding Maryland's performance.

```{r}
library(RSQLite)
library(tidyverse)
library(DBI)

db <- dbConnect(RSQLite::SQLite(), "gymternet.db")


dbListTables(db)

teams <- dbGetQuery(db, 'SELECT * FROM teams')
gymnasts <- dbGetQuery(db, 'SELECT * FROM gymnasts')
gymnast_results <- dbGetQuery(db, 'SELECT * FROM gymnast_results')
meets <- dbGetQuery(db, 'SELECT * FROM meets')
team_results <- dbGetQuery(db, 'SELECT * FROM team_results')
```
